spring.application.name=BookMySlot
spring.datasource.url=jdbc:postgresql://localhost:5432/bookmyslot
spring.datasource.username=postgres
spring.datasource.password=241616

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true